---
- name: Remote RPM install with yum
  yum: name=https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm

- name: Install postgresql
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - postgresql10-server
      - postgresql10-contrib
      - python-psycopg2
      - unzip
    state: present

- name: run initdb 
  command: /usr/pgsql-10/bin/postgresql-10-setup initdb

- name: Configure host based authentication (if entries are configured).
  template:
    src: "pg_hba.conf.j2"
    dest: "/var/lib/pgsql/10/data/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: 0600

- name: Enable the Sonarqube service
  systemd:
    state: started
    enabled: yes
    daemon_reload: yes
    name: postgresql-10

- name: Create a PostgreSQL database user
  postgresql_user: name="{{ sonar_db_user }}" password="{{ sonar_db_pass }}" role_attr_flags=superuser state=present
  become: yes
  become_user: postgres
  become_method: sudo

- name: Create sonarqube database
  become: yes
  become_user: postgres
  postgresql_db:
    name: "{{ sonar_db_name }}"
    encoding: UTF-8
    owner: sonar

- name: grant access sonarqube database
  become: yes
  become_user: postgres
  postgresql_privs:
    db: "{{ sonar_db_name }}"
    state: present
    priv: ALL
    role: sonar
    type: database
